version: '3'

services:
    unbound:
        build: './unbound'
        cap_add:
            - NET_BIND_SERVICE      
            - SETGID
        cap_drop:
            - ALL
        network_mode: host
        volumes:
            - './unbound.conf:/usr/local/etc/unbound/unbound.conf:ro'
